version: '3'

services:
  maven:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    environment:
      - NEXUS_SECURITY_REALM=MyRealm
      - NEXUS_SECURITY_SYSTEM_USERNAME=admin
      - NEXUS_SECURITY_SYSTEM_PASSWORD=myPassword123
